import { CT1_U, CT1_JU, CT2_I, CT2_II } from './base-verbs.js'
import { BaseEnglishVerb, BaseRussianVerb } from './base-verbs.js'

export const EnglishVerbs = {
  become: new BaseEnglishVerb("become", "became", "become"),
  begin: new BaseEnglishVerb("begin", "began", "begun"),
  bring: new BaseEnglishVerb("bring", "brought"),
  buy: new BaseEnglishVerb("buy", "bought"),
  come: new BaseEnglishVerb("come", "came", "come"),
  cut: new BaseEnglishVerb("cut", "cut"),
  do: new BaseEnglishVerb("do", "did", "done"),
  feel: new BaseEnglishVerb("feel", "felt"),
  find: new BaseEnglishVerb("find", "found"),
  fly: new BaseEnglishVerb("fly", "flew", "flown"),
  forget: new BaseEnglishVerb("forget", "forgot", "forgoten"),
  forgive: new BaseEnglishVerb("forgive", "forgave", "forgiven"),
  give: new BaseEnglishVerb("give", "gave", "given"),
  go: new BaseEnglishVerb("go", "went", "gone"),
  have: new BaseEnglishVerb("have", "had"),
  hear: new BaseEnglishVerb("hear", "heard"),
  hold: new BaseEnglishVerb("hold", "held"),
  keep: new BaseEnglishVerb("keep", "kept"),
  kiss: new BaseEnglishVerb("kiss"),
  know: new BaseEnglishVerb("know", "knew", "known"),
  leave: new BaseEnglishVerb("leave", "left"),
  look: new BaseEnglishVerb("look"),
  lose: new BaseEnglishVerb("lose", "lost"),
  love: new BaseEnglishVerb("love"),
  meet: new BaseEnglishVerb("meet", "met"),
  pay: new BaseEnglishVerb("pay", "paid"),
  read: new BaseEnglishVerb("read", "read"),
  see: new BaseEnglishVerb("see", "saw", "seen", "seeing"),
  sleep: new BaseEnglishVerb("sleep", "slept"),
  speak: new BaseEnglishVerb("speak", "spoke", "spoken"),
  think: new BaseEnglishVerb("think", "thought"),
  take: new BaseEnglishVerb("take", "took", "taken"),
  tell: new BaseEnglishVerb("tell", "told"),
  want: new BaseEnglishVerb("want"),
  win: new BaseEnglishVerb("win", "won"),
  work: new BaseEnglishVerb("work")
};

export const RussianVerbs = {
  become: new BaseRussianVerb("становиться", "станов", CT1_JU, CT2_II, "станови"),
  begin: new BaseRussianVerb("начинать", "начина", CT1_JU, CT2_I),
  bring: new BaseRussianVerb("приносить", "принос", CT1_U, CT2_II, "приноси"),
  buy: new BaseRussianVerb("покупать", "покупа", CT1_JU, CT2_I),
  come: new BaseRussianVerb("приходить", "приход", CT1_U, CT2_II, "приходи"),
  cut: new BaseRussianVerb("резать", "реж", CT1_U, CT2_I, "реза"),
  do: new BaseRussianVerb("делать", "дела", CT1_JU, CT2_I),
  feel: new BaseRussianVerb("чувствовать", "чувству", CT1_JU, CT2_I, "чувствова"),
  find: new BaseRussianVerb("находить", "наход", CT1_U, CT2_II, "находи"),
  fly: new BaseRussianVerb("летать", "лета", CT1_JU, CT2_I),
  forget: new BaseRussianVerb("забывать", "забыва", CT1_JU, CT2_I),
  forgive: new BaseRussianVerb("прощать", "проща", CT1_JU, CT2_I),
  give: new BaseRussianVerb("давать", "да", CT1_JU, CT2_I, "дава"),
  go: new BaseRussianVerb("идти", "ид", CT1_U, CT2_I, "ш", {
    past: { singular: { default: { masculine: "шел" } } }
  }),
  have: new BaseRussianVerb("иметь", "име", CT1_JU, CT2_I),
  hear: new BaseRussianVerb("слышать", "слыш", CT1_U, CT2_II, "слыша"),
  hold: new BaseRussianVerb("держать", "держ", CT1_U, CT2_II, "держа"),
  keep: new BaseRussianVerb("хранить", "хран", CT1_JU, CT2_II, "храни"),
  kiss: new BaseRussianVerb("целовать", "целу", CT1_JU, CT2_I, "целова"),
  know: new BaseRussianVerb("знать", "зна", CT1_JU, CT2_I),
  leave: new BaseRussianVerb("оставлять", "оставля", CT1_JU, CT2_I),
  look: new BaseRussianVerb("смотреть", "смотр", CT1_JU, CT2_II, "смотре"),
  lose: new BaseRussianVerb("терять", "теря", CT1_JU, CT2_I),
  love: new BaseRussianVerb("любить", "люб", CT1_JU, CT2_II, "люби"),
  meet: new BaseRussianVerb("встречать", "встреча", CT1_JU, CT2_I),
  pay: new BaseRussianVerb("платить", "плат", CT1_U, CT2_II, "плати"),
  read: new BaseRussianVerb("читать", "чита", CT1_JU, CT2_I),
  see: new BaseRussianVerb("видеть", "вид", CT1_U, CT2_II, "виде"),
  shave: new BaseRussianVerb("брить", "бре", CT1_JU, CT2_I, "бри"),
  sleep: new BaseRussianVerb("спать", "сп", CT1_JU, CT2_II, "спа"),
  speak: new BaseRussianVerb("говорить", "говор", CT1_JU, CT2_II, "говори"),
  think: new BaseRussianVerb("думать", "дума", CT1_JU, CT2_I),
  take: new BaseRussianVerb("брать", "бер", CT1_U, CT2_I, "бра"),
  tell: new BaseRussianVerb("рассказывать", "рассказыва", CT1_JU, CT2_I),
  want: new BaseRussianVerb("хотеть", "хоч", CT1_U, CT2_I, "хоте", {
    present: { plural: {
      first: { default: "хотим" },
      second: { default: "хотите" },
      third: { default: "хотят" }
    } }
  }),
  win: new BaseRussianVerb("выигрывать", "выигрыва", CT1_JU, CT2_I),
  work: new BaseRussianVerb("работать", "работа", CT1_JU, CT2_I)
};
